services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: splitwise
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
      
  backend:
    build: ./backend                    
    depends_on:
      db:
        condition: service_healthy                              
    ports:
      - "8000:8000"                     

  frontend:
    build: ./frontend                   
    ports:
      - "5173:80"                     

volumes:
  pgdata: